"""
replay_db.py — File-based storage for topic replay runs.

Each replay is a parallel trajectory through a topic's evidenceLog under a
chosen lens, generated by `skills/rebuild-topic.md`. Replays are stored as
JSON files in canvas/replays/ so the canvas UI can read them directly.

File naming: <slug>__<lens>__<run_id>.json

Schema (one file = one replay):
{
  "topic_slug": "...",
  "lens": "AMBER",
  "run_id": "20260426T203619Z",          # ISO-derived; unique per run
  "started_at": "2026-04-26T20:36:19Z",
  "finished_at": "...",
  "status": "running" | "complete" | "failed",
  "n_generators": 3,                      # subagents per evidence entry
  "n_critics": 1,
  "evidence_walked": 12,                  # entries that successfully updated
  "evidence_skipped": 3,                  # entries skipped (gate fired, range too wide, etc)
  "skips": [
    { "evidence_id": "ev_007", "reason": "range_too_wide", "detail": "..." }
  ],
  "subagent_proposals": [                 # raw audit trail (optional, large)
    { "evidence_id": "ev_001", "generators": [{H1: 0.3, ...}, ...], "critic_flags": [...] }
  ],
  "posteriorTrajectory": [                # mirrors topic.model.posteriorHistory shape
    { "date": "...", "timestamp": "...", "posteriors": {...},
      "lrSource": {"lens": "AMBER", "source": "replay"},
      "lr_range": {...}, "evidence_refs": [...],
      "dominantHypothesisStable": true, "sensitivityFlag": false,
      "note": "..." }
  ],
  "finalPosteriors": {...},
  "brierAtResolution": null | {           # only if topic is RESOLVED
    "resolved": "H2",
    "perEntryBrier": [0.12, 0.10, ...],   # per posteriorTrajectory entry
    "meanBrier": 0.11
  }
}
"""

import json
import re
from pathlib import Path
from datetime import datetime, timezone

REPO_ROOT = Path(__file__).parent.parent
REPLAYS_DIR = REPO_ROOT.parent / "canvas" / "replays"


def _safe(s: str) -> str:
    return re.sub(r"[^A-Za-z0-9_-]", "_", str(s))[:64] or "x"


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def new_run_id() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")


def replay_path(topic_slug: str, lens: str, run_id: str) -> Path:
    REPLAYS_DIR.mkdir(parents=True, exist_ok=True)
    return REPLAYS_DIR / f"{_safe(topic_slug)}__{_safe(lens)}__{_safe(run_id)}.json"


def list_replays(topic_slug: str = None) -> list[dict]:
    """Return summaries of all replays (optionally filtered to one topic)."""
    if not REPLAYS_DIR.exists():
        return []
    out = []
    pattern = f"{_safe(topic_slug)}__*.json" if topic_slug else "*.json"
    for path in sorted(REPLAYS_DIR.glob(pattern)):
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
            out.append({
                "topic_slug": data.get("topic_slug"),
                "lens": data.get("lens"),
                "run_id": data.get("run_id"),
                "status": data.get("status"),
                "started_at": data.get("started_at"),
                "finished_at": data.get("finished_at"),
                "evidence_walked": data.get("evidence_walked", 0),
                "evidence_skipped": data.get("evidence_skipped", 0),
                "finalPosteriors": data.get("finalPosteriors"),
                "brierAtResolution": data.get("brierAtResolution"),
                "path": str(path.relative_to(REPO_ROOT.parent)),
            })
        except Exception:
            continue
    return out


def load_replay(topic_slug: str, lens: str, run_id: str) -> dict:
    path = replay_path(topic_slug, lens, run_id)
    if not path.exists():
        raise FileNotFoundError(str(path))
    return json.loads(path.read_text(encoding="utf-8"))


def save_replay(replay: dict) -> Path:
    """Write a replay dict to disk; updates finished_at if status=complete.
    Also rewrites canvas/replays/manifest.json so the canvas can list replays."""
    required = ("topic_slug", "lens", "run_id")
    missing = [k for k in required if not replay.get(k)]
    if missing:
        raise ValueError(f"replay missing required fields: {missing}")
    if replay.get("status") == "complete" and not replay.get("finished_at"):
        replay["finished_at"] = _now_iso()
    path = replay_path(replay["topic_slug"], replay["lens"], replay["run_id"])
    path.write_text(json.dumps(replay, indent=2, default=str), encoding="utf-8")
    _write_manifest()
    return path


def _write_manifest() -> None:
    """Rebuild canvas/replays/manifest.json from disk."""
    manifest = {
        "_updated": _now_iso(),
        "replays": list_replays(),
    }
    manifest_path = REPLAYS_DIR / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2, default=str), encoding="utf-8")


def init_replay(topic_slug: str, lens: str, n_generators: int = 3,
                n_critics: int = 1) -> dict:
    """Construct a fresh replay record at started_at; caller fills the rest."""
    return {
        "topic_slug": topic_slug,
        "lens": lens,
        "run_id": new_run_id(),
        "started_at": _now_iso(),
        "finished_at": None,
        "status": "running",
        "n_generators": n_generators,
        "n_critics": n_critics,
        "evidence_walked": 0,
        "evidence_skipped": 0,
        "skips": [],
        "subagent_proposals": [],
        "posteriorTrajectory": [],
        "finalPosteriors": None,
        "brierAtResolution": None,
    }


def derive_lr_range_from_samples(samples: list[dict]) -> dict:
    """
    Given N subagent LR proposals (each a {H1: lr, H2: lr, ...} dict),
    return:
      {
        "point": {H1: median, ...},
        "lo": {H1: min, ...},
        "hi": {H1: max, ...},
        "width_per_h": {H1: max-min, ...},
        "max_width": float
      }

    Caller decides what to do if max_width is too large (skip the entry).
    """
    if not samples:
        raise ValueError("no samples")
    h_keys = list(samples[0].keys())
    lo = {}
    hi = {}
    point = {}
    width_per_h = {}
    for k in h_keys:
        vals = sorted([float(s.get(k, 0.0)) for s in samples])
        lo[k] = vals[0]
        hi[k] = vals[-1]
        # median (no interpolation; tolerant of N=3)
        n = len(vals)
        point[k] = vals[n // 2] if n % 2 == 1 else (vals[n // 2 - 1] + vals[n // 2]) / 2
        width_per_h[k] = hi[k] - lo[k]
    return {
        "point": point,
        "lo": lo,
        "hi": hi,
        "width_per_h": width_per_h,
        "max_width": max(width_per_h.values()) if width_per_h else 0.0,
    }


def promote_replay_to_live(topic: dict, replay: dict) -> dict:
    """
    Replace topic.model.posteriorHistory with the replay's posteriorTrajectory,
    and update topic.model.hypotheses[*].posterior to the replay's
    finalPosteriors. Snapshots the prior live trajectory under
    topic.model._preReplayHistory so promotion is reversible.

    Mutates and returns the topic. Caller must save_topic() after.
    """
    if replay.get("status") != "complete":
        raise ValueError(f"replay status is {replay.get('status')!r}, must be 'complete'")
    if replay.get("topic_slug") != topic.get("meta", {}).get("slug"):
        raise ValueError("replay slug mismatch with topic")
    final_posteriors = replay.get("finalPosteriors") or {}
    if not final_posteriors:
        raise ValueError("replay has no finalPosteriors")
    model = topic.setdefault("model", {})
    # Snapshot prior live history under a recoverable key
    model["_preReplayHistory"] = model.get("posteriorHistory", [])
    model["_preReplayPosteriors"] = {
        k: h.get("posterior") for k, h in (model.get("hypotheses") or {}).items()
    }
    model["_replayPromotedFrom"] = {
        "lens": replay.get("lens"),
        "run_id": replay.get("run_id"),
        "promoted_at": _now_iso(),
    }
    # Replace
    model["posteriorHistory"] = list(replay.get("posteriorTrajectory") or [])
    for k, p in final_posteriors.items():
        if k in model.get("hypotheses", {}):
            model["hypotheses"][k]["posterior"] = float(p)
    return topic
